#!/usr/bin/python2.4
# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2



_AD_REQ_T = descriptor.Descriptor(
  name='ad_req_t',
  full_name='ad_msg.ad_req_t',
  filename='msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='req_json_str', full_name='ad_msg.ad_req_t.req_json_str', index=0,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_AD_RES_T_BID_INFO_T = descriptor.Descriptor(
  name='bid_info_t',
  full_name='ad_msg.ad_res_t.bid_info_t',
  filename='msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='bid', full_name='ad_msg.ad_res_t.bid_info_t.bid', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ad_type', full_name='ad_msg.ad_res_t.bid_info_t.ad_type', index=1,
      number=2, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='height', full_name='ad_msg.ad_res_t.bid_info_t.height', index=2,
      number=3, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='width', full_name='ad_msg.ad_res_t.bid_info_t.width', index=3,
      number=4, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='click_type', full_name='ad_msg.ad_res_t.bid_info_t.click_type', index=4,
      number=5, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='idea_id', full_name='ad_msg.ad_res_t.bid_info_t.idea_id', index=5,
      number=6, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='click_url', full_name='ad_msg.ad_res_t.bid_info_t.click_url', index=6,
      number=7, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_AD_RES_T = descriptor.Descriptor(
  name='ad_res_t',
  full_name='ad_msg.ad_res_t',
  filename='msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='status', full_name='ad_msg.ad_res_t.status', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='err_msg', full_name='ad_msg.ad_res_t.err_msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bid_response', full_name='ad_msg.ad_res_t.bid_response', index=2,
      number=3, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_AD_RES_T.fields_by_name['bid_response'].message_type = _AD_RES_T_BID_INFO_T

class ad_req_t(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AD_REQ_T

class ad_res_t(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class bid_info_t(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _AD_RES_T_BID_INFO_T
  DESCRIPTOR = _AD_RES_T

